### ISSUE TITLE
Error using the Template

### ISSUE THREAD

**Issue by ebeagusamuel** [justalever/kickoff_tailwind#10] opened 2020-07-25 15:00 UTC
Hi @justalever. 
I tried using the template to create a new rails app but i keep getting an error when it gets to this point in the installing ` run  mkdir -p app/javascript/stylesheets from "."`.
Here is what is been displayed before the installation is cut off `The file /home/ebeagusamuel/Documents/kickoff_tailwind/demo/app/javascript/packs/application.js does not appear to exist`. I have no idea what is causing the issue. 
Will be grateful if you can help me with this.

Thanks for all you do, your tutorials have been really helpful.

**Comment by justalever** [comment] 2020-07-25 18:37
Hey @ebeagusamuel,

Are you generating the app locally and pointing to GitHub directly by chance?

I typically clone the repo and create a new app inside it. I still need to work out the kinks on the remote version.

Example 

```bash
rails new my_app -m kickoff_tailwind/template.rb
```

**Comment by ebeagusamuel** [comment] 2020-07-25 23:30
Thanks for the Swift reply.
I cloned the repo and am creating the new app inside the the cloned repo's directory.

**Comment by justalever** [comment] 2020-08-03 14:47
Thanks for confirming @ebeagusamuel . I can't seem to reproduce the issue. Any chance you got this sorted?

**Comment by bear-in-mind** [comment] 2020-09-17 12:58
I'm having issues in production with my own project, and landed on this repo. Out of curiosity, I cloned it and generated a new app with this template but ended up with the same problem : there's a 404 on the `application.js` as well... I'm out of luck !

**Comment by bahasalien** [comment] 2020-11-05 05:36
same here still figured how....

**Comment by bahasalien** [comment] 2020-11-05 13:25
it fix just delete this for everyone facing problem...

```
  run "mkdir -p app/javascript/stylesheets"

  append_to_file("app/javascript/packs/application.js", 'import "stylesheets/application"')
  inject_into_file("./postcss.config.js",
  "let tailwindcss = require('tailwindcss');\n",  before: "module.exports")
  inject_into_file("./postcss.config.js", "\n    tailwindcss('./app/javascript/stylesheets/tailwind.config.js'),", after: "plugins: [")

  run "mkdir -p app/javascript/stylesheets/components"
```
and replaces the file app/javascript with https://github.com/justalever/kickoff_tailwind

don't forget postcss.config.js too...

very well done fix to me.

**Comment by justalever** [comment] 2020-11-26 17:54
This has since been updated so I'll go ahead and close this issue.

**Closed by justalever** 2020-11-26 17:54 UTC

**Comment by Rex-am-I** [comment] 2021-02-01 09:25
I am encountering the exact same error even after I cloned it.
